contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ngsflows channel"
    url: https://nfcore.slack.com/channels/ngsflows
    about: Discussion about the nf-core/ngsflows pipeline
